## Evento Tanker
#
#Desenvolvido por: Arthur Amorim
#Discord: Arthur Amorim#9378
#Versao do plugin: 1.0
#
#Suporte para SimpleClans e legendChat"
#para usar a tag no legenchat colocar {tanker} na configuracao default
#


maxPlayer: 5
minStart: 2
priceAcess: 1
announcer: 2
timerAnnouncer: 10
tag: "&d[Tanker]"

cabin:
  world: "world"
  x: 224.0
  y: 75.0
  z: 267.0
arena:
  world: "world"
  x: 230.5
  y: 73.0
  z: 277.5

set:
  helmet:
    id: 302
    data: 0
    enchantList:
      - 'DURABILITY,1'
  armor:
    id: 303
    data: 0
    enchantList:
      - 'DURABILITY,1'
  legs:
    id: 304
    data: 0
    enchantList:
      - 'DURABILITY,1'
  boots:
    id: 305
    data: 0
    enchantList:
      - 'DURABILITY,1'
  weapon:
    id: 272
    data: 0
    enchantList:
      - 'FIRE_ASPECT,1'
      - 'DURABILITY,1'

items:
  1:
    id: 322
    data: 0
    quantity: 1

reward:
  coins: 1000
  commandEnable: true
  cmds:
    - 'dsadsa %player%'
  itemEnable: true
  items:
    1:
      id: 272
      data: 0
      name: "Espada Tanker"
      quantity: 1
      enchantList:
        - 'FIRE_ASPECT,1'
      lore:
        - '&bRecompensa do evento tanker'
    2:
      id: 1
      data: 0
      name: "Pedra Tanker"
      quantity: 64
      enchantList: []
      lore: []

messages:
  canceled: "&cEvento cancelado por um staff"
  not_have_min: "&cEvento cancelado por nao atingir o minimo de participantes."
  not_started: "&cEvento nao iniciado"
  start: "&aEvento iniciado, que o melhor participante vença"
  close: "&eEvento fechado, participantes se preparem!"
  join_event: "&aVoce agora esta participando do evento! Aguarde o teleport."
  leave_event: "&cVoce saiu do evento."
  removed_from_event: "&cVoce foi removido do evento por estar com itens no seu inventario"
  items_in_inv: "&cVoce nao pode entrar no evento com items no inventario"
  not_have_money: "&cVoce nao tem coins suficientes para entrar no evento"
  winner: "&aO jogador %player% venceu o evento!"
  is_participant: "&eVocê ja esta participando do evento"
  is_started: "&aO evento ja foi iniciado"
  not_have_permission: "&cVoce nao tem permissao"
  max_participants: "&cO evento atingiu o limite de participantes."
  elimined: "&eVoce foi eliminado por %killer%"

lastWinner: "TheArthur"