maxPlayer: 0
minStart: 5
priceAcess: 10000
announcer: 3
timerAnnouncer: 30

position:
  world: "world"
  x: 224.0
  y: 75.0
  z: 267.0

reward:
  commandEnable: true
  cmds:
    - 'a'
  itemEnable: true
  items:
    1:
      id: 1
      data: 0
      quantity: 1
      enchantList: []
      lore:
        - '&bRecompensa do evento tanker'